version: '3.8'

services:
  tennis-stats-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tennis-db-dev
    ports:
      - '5432:5432'
    volumes:
      - tennis-db-dev:/var/lib/postgresql/data
volumes:
  tennis-db-dev:
    driver: local