greeting:
  message: "hello"

quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/tennis-db-dev
  swagger-ui:
    enable: true
  http:
    port: 8888
  hibernate-orm:
    database:
      generation: update
  live-reload:
    instrumentation: true
    url: localhost:8889