greeting:
  message: "hello"

firebase:
  credential:
    path: src/main/resources/firestore/serviceAccount.json

quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/tennis-db-dev
  swagger-ui:
    enable: true
  http:
    port: 8888
    auth:
      permission:
        getPermission:
          paths: /api/*
          policy: permit
          enabled: true
          methods: GET
        updatePermission:
          paths: /api/*
          policy: permit
          enabled: true
          methods: POST,PUT,DELETE
      basic: true
      policy:
        adminPolicy:
          roles-allowed: admin
  hibernate-orm:
    database:
      generation: update
  package:
    type: uber-jar